# Generated by Django 6.0.3 on 2026-04-03 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempt',
            name='assessment_type',
            field=models.CharField(choices=[('baseline', 'Baseline'), ('practice', 'Practice')], default='practice', max_length=20),
        ),
        migrations.AddField(
            model_name='userattempt',
            name='attempted_difficulty',
            field=models.CharField(default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='userattempt',
            name='mistake_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='BehavioralDatasetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('baseline', 'Baseline'), ('practice', 'Practice')], max_length=20)),
                ('sample_count', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('mistake_type_counts', models.JSONField(blank=True, default=dict)),
                ('difficulty_distribution', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
