# Generated by Django 6.0.3 on 2026-04-03 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userattempt_assessment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveLearningState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_difficulty', models.CharField(default='easy', max_length=20)),
                ('trend_status', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20)),
                ('accuracy_delta', models.FloatField(default=0.0)),
                ('response_time_delta', models.FloatField(default=0.0)),
                ('correct_streak', models.IntegerField(default=0)),
                ('incorrect_streak', models.IntegerField(default=0)),
                ('last_feedback', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
